import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import manifest from './asset-manifest.json';

/**
 * Content-hashed URL for a file in public/.
 *
 * Hand-maintained `?v=3` query strings go stale the moment someone edits the
 * asset and forgets to bump the number — and the failure is invisible, because
 * the server is serving correct CSS that returning browsers never fetch. That
 * happened here: four consecutive fixes to style.css all shipped under `?v=3`,
 * so the marquee stayed broken for anyone with a warm cache while measuring
 * correct in a fresh one.
 *
 * Deriving the query from the file's own bytes makes that impossible: change
 * the file, the URL changes, caches invalidate.
 *
 * The hashing itself now happens at build time, in scripts/build-asset-manifest.mjs,
 * rather than here at render time. It had to move for Cloudflare: public/ is
 * uploaded to Workers Static Assets, not bundled into the Worker, so a runtime
 * fs.readFileSync(process.cwd() + '/public' + …) finds nothing and every asset
 * on a runtime-rendered route would ship as `?v=missing` — silently, and only
 * for returning visitors. Reading a bundled manifest has no such failure mode,
 * and it is also simply faster: no I/O and no sha1 per render.
 *
 * The algorithm and output format are unchanged, so every URL this returns is
 * byte-identical to what the filesystem version produced.
 */
const versions: Record<string, string> = manifest;

/**
 * Dev keeps hashing live.
 *
 * The manifest is regenerated by `prebuild`, so during `next dev` it is exactly
 * as stale as your last build — meaning an edit to style.css would keep serving
 * the old query string, and you would be looking at a cached stylesheet while
 * debugging why your change did nothing. Hashing on demand costs one small read
 * per asset in dev and removes that trap entirely.
 *
 * `process.env.NODE_ENV` is statically replaced at build time, so the body of
 * this branch is dead code in a production build. The node:fs/path/crypto
 * imports stay at the top rather than being lazily required: they cost nothing
 * in the Worker, where nodejs_compat provides them from the runtime instead of
 * bundling them, and a dynamic require inside an ESM package ("type": "module")
 * is a real failure mode for no real saving.
 */
function devVersion(publicPath: string): string | undefined {
  if (process.env.NODE_ENV === 'production') return undefined;
  try {
    const file = path.join(process.cwd(), 'public', publicPath.replace(/^\//, ''));
    return createHash('sha1').update(fs.readFileSync(file)).digest('hex').slice(0, 8);
  } catch {
    return undefined;
  }
}

export function asset(publicPath: string): string {
  const version = devVersion(publicPath) ?? versions[publicPath];

  if (!version) {
    // A missing asset is a real problem, but it is the console/content audits'
    // job to fail on it — not the layout's. Render a traceable marker instead.
    console.error(`[asset] not in manifest: ${publicPath} — run \`npm run assets:manifest\``);
    return `${publicPath}?v=missing`;
  }

  return `${publicPath}?v=${version}`;
}
