import type { Metadata } from 'next';
import type { Locale } from './blocks';
import { getSettings } from './content';

/** Canonical origin for canonicals, hreflang, the sitemap and OG urls. */
export const SITE_ORIGIN = process.env.SITE_ORIGIN ?? 'https://www.3lines.com.sa';

/**
 * Short brand name, from Site info in the CMS. The literal fallback only fires
 * on a settings file that predates the key — it is not a second source of
 * truth, just a guard against rendering an empty <title>.
 */
export function siteName(locale: Locale): string {
  const s = getSettings();
  return s.siteName?.[locale] || s.siteName?.en || '3Lines Advanced Technologies';
}

/** The suffix in the title template ("About | 3Lines"). */
export function titleBrand(): string {
  return getSettings().titleBrand || '3Lines';
}

const OG_LOCALE: Record<Locale, string> = { en: 'en_US', ar: 'ar_SA' };

/**
 * The Open Graph block for a page.
 *
 * Next merges metadata **shallowly**: an `openGraph` returned by a child segment
 * replaces the parent's outright instead of extending it. The layout set
 * `siteName`, `locale` and `type`; every real page then returned its own
 * `openGraph` for title/description/url — so those three were dropped from the
 * head of every page on the site, and the file-based share card was dropped with
 * them. `og:image` was absent everywhere, which is why links unfurled bare.
 *
 * Assembling the whole block in one place is what makes that non-recurring: the
 * segment that overrides is the segment that gets the complete object, and the
 * image is named explicitly rather than relying on the file convention surviving
 * a merge it does not survive.
 */
export function openGraph(
  locale: Locale,
  { title, description, path }: { title: string; description?: string; path: string }
): Metadata['openGraph'] {
  return {
    title,
    description,
    url: `${SITE_ORIGIN}${path}`,
    siteName: siteName(locale),
    locale: OG_LOCALE[locale],
    alternateLocale: OG_LOCALE[locale === 'ar' ? 'en' : 'ar'],
    type: 'website',
    images: [
      {
        // Generated by app/[locale]/opengraph-image.tsx. Relative, so
        // `metadataBase` resolves it against whichever origin is deployed.
        url: `/${locale}/opengraph-image`,
        width: 1200,
        height: 630,
        alt: siteName(locale),
      },
    ],
  };
}
